### ISSUE TITLE
Rédaction et validation du dossier d'architectures techniques et fonctionnelles

### ISSUE THREAD

**Issue by lilouNait** [EzekielaRakotoarijaona/OlapMod#11]

**Comment by EzekielaRakotoarijaona** [comment]
Le DAT est disponible à l'adresse suivante : https://docs.google.com/document/d/1t0T7fK3ZXeUefo5h-r6V9Pbm9InxuuDtTCRrIeVIHsE/edit#heading=h.4vmji93fr8we
