### ISSUE TITLE
Rédaction du planning projet

### ISSUE THREAD

**Issue by lilouNait** [EzekielaRakotoarijaona/OlapMod#13]

**Comment by cehochet** [comment]
A faire : 
- Roadmap
- Jalon

**Comment by cehochet** [comment]
Date des jalons : https://docs.google.com/spreadsheets/d/1RBncxWaBHoesjeq_8fh5ZJif5r61Qkm9/edit#gid=1027813173 
Réunion de projets : https://docs.google.com/spreadsheets/d/1RBncxWaBHoesjeq_8fh5ZJif5r61Qkm9/edit#gid=1346784025
