### ISSUE TITLE
Etude des documents fourni par Maabuot

### ISSUE THREAD

**Issue by EzekielaRakotoarijaona** [EzekielaRakotoarijaona/OlapMod#3]
Compréhension du sujet et des documents par rapport au besoin du client

**Comment by cehochet** [comment]
Cours : [Projet.pdf](https://github.com/EzekielaRakotoarijaona/OlapMod/files/4392495/Projet.pdf)

**Comment by cehochet** [comment]
**L'objectif du projet est : Etant donnée une table de fait, l’objectif est d'optimiser le temps des requêtes.** 

Pour cela on va pré-calculer et stocker des requêtes pour trouver le **minimal query cost**.
**Problème** : Ce pré-calcule est très gourmand en mémoire. 

**Solution** : Ainsi, on va devoir trouver un sous-ensemble parmi les requêtes restantes (outre la table de fait), qui ne va pas occuper trop d'espace mémoire et pour qui le pré-calcul va réduire au max toutes les requêtes. 

L'algorithme en question passe en paramètre : 1. La table de fait et 2. Nombre de requêtes. Et la sortie est : @lilouNait (Peux-tu compléter ? )

Pour cet algorithme nous avons besoin de connaître la taille d'une requête (cf tâche tester le programme C++ #4 ).

**Comment by beyy18** [comment]
**Question pour la réunion 2**
A quoi sert la conversion binaire dans le code ?
