### ISSUE TITLE
Dégager un algorithme des meilleurs requêtes à pré-calculer 

### ISSUE THREAD

**Issue by EzekielaRakotoarijaona** [EzekielaRakotoarijaona/OlapMod#5]
A partir du résultat de l'algorithme de #4, essayer de trouver un algorithme permettant de trouver les meilleures requêtes à pré-calculer en fonction d'une taille de mémoire donnée

**Comment by cehochet** [comment]
Petit document sur l'OLAP et ces trois sous-système : ROLAP - MOLAP - HOLAP
[5-SystemesOLAP-4p.pdf](https://github.com/EzekielaRakotoarijaona/OlapMod/files/4401961/5-SystemesOLAP-4p.pdf)

**Comment by beyy18** [comment]
**Calcul coût min de mémoire**

- Le choix de combinaison pour calculer le coût de mémoire est fait en fonction du nombre de colonnes/dimensions de la table initiale.

- Il suffit de choisir 3 combinaisons parmi les 8 en s'assurant que toute combinaison est "saturée"

- Pour retrouver le minimum coût de mémoire, il faut comparer les valeurs trouvées précédemment et les comparer avec le nouveau. Le minimum sera stocké dans une variable. Ainsi de suite...

**Comment by EzekielaRakotoarijaona** [comment]
Potentiellement utiliser la théorie des graphes avec le plus court chemin pour avoir les requêtes qui seront les moins couteuses
