### ISSUE TITLE
Renommer le nom de la popup "fichier enregistré"

### ISSUE THREAD

**Issue by lilouNait** [EzekielaRakotoarijaona/OlapMod#72]
Renommer le nom de la popup "fichier enregistré" avec un nom plus adéquat, par exemple "information" ou supprimer carrément le titre
Se referer au cahier de test executé dans la tache #60 et dans le test 8 pour comprendre plus en détails le bug

**Comment by cehochet** [comment]
La fenêtre a été renommé avec le nom de l'application : QueryOptimizer
